/* ============================================================
   Boston AI Atlas — community dataset
   ------------------------------------------------------------
   To add an entry: copy an existing object, fill in every field,
   and open a pull request. Full instructions: CONTRIBUTING.md
   Validate locally with:  node scripts/validate.js
   ------------------------------------------------------------
   Entry fields:
     id      unique kebab-case string
     name    display name
     cat     one of the CATS keys below
     loc     address or neighborhood label
     lat,lng coordinates (Greater Boston)
     approx  true if coordinates are neighborhood-level
     url     official https:// website
     badge   optional highlight, e.g. "Applications open"
     desc    1-2 sentence factual description
     why     why it matters for founders
     tags    2-4 short lowercase tags
     stages  founder stages 1-5 where this resource helps
     links   ids of related entries (drawn in Galaxy view)
     lastVerified
             the month ("YYYY-MM") a maintainer last confirmed the org
             is real, active, and the entry's facts are right — set it
             when you actually checked the org, not merely when you
             edited the entry
   ============================================================ */
const CATS = {
  startup:   {label:"AI Companies & Startups", color:"#5eead4"},
  vc:        {label:"Venture Capital",          color:"#a78bfa"},
  angel:     {label:"Angel Groups",             color:"#f472b6"},
  accel:     {label:"Accelerators & Founder Support", color:"#fbbf24"},
  university:{label:"University Labs & Centers",color:"#60a5fa"},
  corporate: {label:"Corporate AI Labs",        color:"#94a3b8"},
  community: {label:"Communities & Meetups",    color:"#4ade80"},
  event:     {label:"Major Events",             color:"#fb923c"},
  gov:       {label:"Government & Policy",      color:"#f87171"},
  space:     {label:"Spaces & Hubs",            color:"#22d3ee"},
  student:   {label:"Student Groups",           color:"#e879f9"}
};

const STAGES = [
  {n:1, t:"Spark", s:"Learn & plug in", icon:"💡",
   desc:"You're curious about AI or just landed in Boston. Goal: build technical depth and a local network before you need either. Boston's superpower is that world-class AI research is open to the public almost every week.",
   tips:[
     ["Show up Thursday","Venture Café Cambridge runs free weekly gatherings — the single fastest way to meet the ecosystem."],
     ["Demo culture","AI Tinkerers and Sundai Club are hands-on: people show what they built. Go watch, then show something."],
     ["Free firepower","MIT & Harvard public lectures and lab open houses are free and unbadged. Use them."]]},
  {n:2, t:"Validate", s:"Test the idea", icon:"🔬",
   desc:"You have an idea and need brutal, useful feedback. Boston's mentor infrastructure is unusually generous — much of it free and equity-free.",
   tips:[
     ["Free mentors","MIT VMS gives team-based mentoring at no cost and takes no equity — alumni connections help but aren't always required at other programs."],
     ["Pitch early, pitch ugly","Angel groups and open pitch nights will pressure-test your story long before you raise."],
     ["Talk to 50 users","Boston is dense with early adopters in health, robotics, biotech, fintech and edtech — your first design partners are on the Red Line."]]},
  {n:3, t:"Build", s:"Team, space & compute", icon:"🔧",
   desc:"Time to make the thing. You need cofounders, space, GPUs, and a prototype. Hackathons are Boston's #1 cofounder matching engine, and the state now subsidizes AI compute.",
   tips:[
     ["Compute is cheaper here","The Mass AI Hub's AICR environment at MGHPCC offers high-performance compute for startups, and The Open Accelerator residency bundles workspace, mentorship and GPU access — apply before buying cloud credits."],
     ["Hardware? MassRobotics.","If your AI touches the physical world, MassRobotics has shared lab space and equipment that would cost you millions."],
     ["Hire from hackathons","HackMIT and HackHarvard teams are pre-vetted builders. Sponsor, mentor, or just hang out."]]},
  {n:4, t:"Fund", s:"Raise your first round", icon:"💸",
   desc:"Pre-seed and seed. Boston has more equity-free money than almost any city — exhaust grants, prizes and accelerators before selling equity.",
   tips:[
     ["Equity-free first","MassChallenge (up to $1M in prizes), delta v ($20K), and state grant programs dilute you 0%."],
     ["AI-native checks","Glasswing, Hyperplane, Converge and Flybridge write seed checks specifically on AI theses — speak their language."],
     ["Angels open doors","Boston angel groups syndicate together; one warm intro often cascades to four groups."]]},
  {n:5, t:"Scale", s:"Grow & lead", icon:"🚀",
   desc:"Product-market fit is emerging; now compound. Boston's late-stage capital, corporate partners and talent pipeline are your levers — and the ecosystem rewards founders who give back.",
   tips:[
     ["Corporate design partners","Google, Microsoft, Meta, IBM and Amazon all run Kendall-area labs with partner programs — land lighthouse customers locally."],
     ["Own a stage","Boston AI Week (Sept–Oct) and ODSC East are where the ecosystem looks for its next champions."],
     ["Recruit the pipeline","MIT, Harvard, Northeastern co-ops and BU ship thousands of AI grads a year. Build your brand on campus early."]]}
];

const DATA = [
// ---------- UNIVERSITY LABS & CENTERS ----------
{id:"csail", name:"MIT CSAIL", cat:"university", loc:"Stata Center, 32 Vassar St, Cambridge",
 lat:42.3617, lng:-71.0906, url:"https://www.csail.mit.edu",
 desc:"MIT's Computer Science & Artificial Intelligence Laboratory — the largest research lab at MIT and one of the most influential AI labs on Earth.",
 why:"Birthplace of countless spinouts (including Liquid AI). Public talks, open events, and researchers who answer cold emails more often than you'd think.",
 tags:["research","spinouts","talks"], stages:[1,3], links:["liquid","tamr","mit-ibm"], lastVerified:"2026-06"},
{id:"medialab", name:"MIT Media Lab", cat:"university", loc:"75 Amherst St, Cambridge",
 lat:42.3606, lng:-71.0873, url:"https://www.media.mit.edu",
 desc:"MIT's antidisciplinary lab mixing AI with design, health, music and society. Hosts major AI gatherings including Imagination in Action.",
 why:"If your AI idea is weird in a good way, this is its spiritual home — and the E14 Fund invests in its spinouts.",
 tags:["research","creative AI"], stages:[1], links:["e14","imagination"], lastVerified:"2026-06"},
{id:"socc", name:"MIT Schwarzman College of Computing", cat:"university", loc:"51 Vassar St, Cambridge",
 lat:42.3614, lng:-71.0926, url:"https://computing.mit.edu",
 desc:"MIT's $1B college uniting computing and AI education across every discipline, in a landmark new building on Vassar Street.",
 why:"The front door to MIT's AI curriculum and cross-disciplinary collaborations.",
 tags:["education","research"], stages:[1], lastVerified:"2026-06"},
{id:"jameel", name:"MIT Jameel Clinic", cat:"university", loc:"Cambridge (MIT campus)",
 lat:42.3621, lng:-71.0898, url:"https://jclinic.mit.edu", approx:true,
 desc:"MIT's epicenter for AI in health — machine learning for drug discovery, diagnostics and clinical care.",
 why:"Health AI founders: their open-source models and clinical partnerships are a map of where healthcare AI is going.",
 tags:["health","research"], stages:[1,2], lastVerified:"2026-06"},
{id:"kempner", name:"Kempner Institute (Harvard)", cat:"university", loc:"150 Western Ave, Allston",
 lat:42.3635, lng:-71.1283, url:"https://kempnerinstitute.harvard.edu",
 desc:"Harvard's institute for the study of natural and artificial intelligence, backed by a $500M Chan-Zuckerberg gift.",
 why:"Frontier research on how intelligence works — and a deep bench of researchers one river-crossing from your startup.",
 tags:["research","neuroscience"], stages:[1], lastVerified:"2026-06"},
{id:"hdsi", name:"Harvard Data Science Initiative", cat:"university", loc:"Harvard Sq, Cambridge",
 lat:42.3782, lng:-71.1140, url:"https://datascience.harvard.edu", approx:true,
 desc:"University-wide hub connecting Harvard's data science and AI research across schools.",
 why:"Seminars and industry partnerships open to the broader community.",
 tags:["research","data science"], stages:[1], lastVerified:"2026-06"},
{id:"berkman", name:"Berkman Klein Center", cat:"university", loc:"23 Everett St, Cambridge",
 lat:42.3782, lng:-71.1190, url:"https://cyber.harvard.edu",
 desc:"Harvard's center for internet & society — a leading voice on AI governance, ethics and policy.",
 why:"If your product touches AI regulation, content, or safety, their fellows and events are your early-warning radar.",
 tags:["policy","ethics"], stages:[1,5], lastVerified:"2026-06"},
{id:"eai", name:"Institute for Experiential AI (Northeastern)", cat:"university", loc:"805 Columbus Ave, Boston",
 lat:42.3373, lng:-71.0883, url:"https://ai.northeastern.edu",
 desc:"Northeastern's applied AI institute focused on human-in-the-loop AI, with strong industry partnership programs.",
 why:"Built for collaboration with companies — a practical path to research talent and co-op hires.",
 tags:["applied AI","talent"], stages:[1,5], lastVerified:"2026-06"},
{id:"bucds", name:"BU Computing & Data Sciences", cat:"university", loc:"665 Commonwealth Ave, Boston",
 lat:42.3505, lng:-71.1054, url:"https://www.bu.edu/cds-faculty/",
 desc:"BU's computing & data sciences faculty in the iconic 'Jenga' tower, alongside the Hariri Institute.",
 why:"A fast-growing AI program in the geographic center of Boston's student population.",
 tags:["education","research"], stages:[1], lastVerified:"2026-06"},
{id:"cics", name:"UMass Amherst Manning CICS", cat:"university", loc:"Amherst, MA",
 lat:42.3954, lng:-72.5318, url:"https://www.cics.umass.edu",
 desc:"UMass Amherst's College of Information & Computer Sciences — a top-tier NLP and IR research powerhouse 90 minutes west.",
 why:"Underrated talent pool; many grads want to stay in Massachusetts.",
 tags:["NLP","talent"], stages:[1], lastVerified:"2026-06"},
{id:"wpi", name:"WPI AI Programs", cat:"university", loc:"Worcester, MA",
 lat:42.2746, lng:-71.8063, url:"https://www.wpi.edu",
 desc:"Worcester Polytechnic Institute — project-based engineering education with dedicated MS in AI.",
 why:"Robotics and applied-AI engineers with hands-on project portfolios.",
 tags:["robotics","talent"], stages:[1], lastVerified:"2026-06"},
{id:"tufts", name:"Tufts CS & HRI Lab", cat:"university", loc:"Medford, MA",
 lat:42.4075, lng:-71.1190, url:"https://engineering.tufts.edu/cs/", approx:true,
 desc:"Tufts computer science, including notable human-robot interaction research.",
 why:"Quietly strong on human-centered AI.",
 tags:["HRI","research"], stages:[1], lastVerified:"2026-06"},

// ---------- CORPORATE AI LABS ----------
{id:"mit-ibm", name:"MIT-IBM Watson AI Lab", cat:"corporate", loc:"314 Main St, Kendall Sq",
 lat:42.3622, lng:-71.0857, url:"https://mitibmwatsonailab.mit.edu",
 desc:"IBM's $240M joint AI research lab with MIT — a flagship model of corporate-academic AI collaboration.",
 why:"Their open research and challenge programs are accessible entry points to both MIT and IBM.",
 tags:["research","partnerships"], stages:[1,5], links:["csail"], lastVerified:"2026-06"},
{id:"nerd", name:"Microsoft New England R&D (NERD)", cat:"corporate", loc:"1 Memorial Dr, Cambridge",
 lat:42.3614, lng:-71.0813, url:"https://www.microsoft.com/en-us/garage/locations/new-england/",
 desc:"Microsoft's Cambridge R&D center — and one of the most generous event venues in the ecosystem.",
 why:"Hosts the Boston Generative AI Meetup and dozens of community events; Microsoft for Startups credits flow through here.",
 tags:["venue","cloud credits"], stages:[1,5], links:["genai-meetup"], lastVerified:"2026-06"},
{id:"google", name:"Google Cambridge", cat:"corporate", loc:"325 Main St, Kendall Sq",
 lat:42.3621, lng:-71.0846, url:"https://about.google/locations/",
 desc:"Google's 2,000+ person Kendall Square campus, with significant AI/ML engineering teams.",
 why:"Google for Startups programs, cloud credits, and a deep local hiring pool of alumni.",
 tags:["engineering","cloud"], stages:[5], lastVerified:"2026-06"},
{id:"meta-cam", name:"Meta Cambridge", cat:"corporate", loc:"100 Binney St, Cambridge",
 lat:42.3672, lng:-71.0805, url:"https://www.metacareers.com/locations/boston",
 desc:"Meta's Cambridge office including AI infrastructure and research engineering teams.",
 why:"PyTorch has deep roots here — the local alumni network is rich with ML infra talent.",
 tags:["ML infra","PyTorch"], stages:[5], lastVerified:"2026-06"},
{id:"amazon-sea", name:"Amazon Boston (Seaport)", cat:"corporate", loc:"111 Harbor Way, Seaport",
 lat:42.3513, lng:-71.0448, url:"https://www.aboutamazon.com",
 desc:"Amazon's Seaport tech hub — Alexa AI heritage plus robotics teams tied to Amazon Robotics in the metro area.",
 why:"AWS Activate credits and a large pool of applied-ML engineers.",
 tags:["AWS","robotics"], stages:[5], lastVerified:"2026-06"},
{id:"rai", name:"RAI Institute", cat:"corporate", loc:"145 Broadway, Kendall Sq",
 lat:42.3650, lng:-71.0851, url:"https://rai-inst.com",
 desc:"The Robotics & AI Institute (founded by Boston Dynamics creator Marc Raibert, Hyundai-backed) doing frontier robot-learning research.",
 why:"One of the world's best-funded robotics AI research orgs is hiring in Kendall Square.",
 tags:["robotics","research"], stages:[1,5], links:["bdyn"], lastVerified:"2026-06"},
{id:"anthropic-bos", name:"Anthropic (Cambridge)", cat:"corporate", loc:"Central Square, Cambridge", approx:true,
  lat:42.3653, lng:-71.1037, url:"https://anthropic.com",
  desc:"Claude AI maker's growing Cambridge office — 25+ employees, mostly PhDs from MIT and Harvard, focused on AI safety and technical development.",
  why:"Rapidly expanding Boston presence. Hosted 'Founders' Lab: AI for Life Sciences' at Boston Tech Week 2026. Key recruiter from local AI talent pool.",
  tags:["AI safety","LLMs","research"], links:[], lastVerified:"2026-06"},
{id:"nvidia-bos", name:"NVIDIA (Westford)", cat:"corporate", loc:"Westford, MA",
  lat:42.5795, lng:-71.4377, url:"https://nvidia.com",
  desc:"GPU and AI infrastructure leader. Greater Boston office focused on networking (Mellanox heritage), data center solutions, and AI enterprise partnerships.",
  why:"Powers most of the AI training and inference infrastructure in the region. Key partner for AI Factory initiatives with Red Hat and hyperscalers.",
  tags:["GPUs","infrastructure","networking"], links:[], lastVerified:"2026-06"},
{id:"oracle-bos", name:"Oracle (Burlington)", cat:"corporate", loc:"Burlington, MA",
  lat:42.5048, lng:-71.1962, url:"https://oracle.com",
  desc:"Major enterprise software employer in Greater Boston. Cloud infrastructure, autonomous database, and AI/ML platform development.",
  why:"Large engineering teams in Burlington. Acquired several Boston-area AI companies. Strong enterprise customer relationships for AI startup partnerships.",
  tags:["cloud","database","enterprise"], links:[], lastVerified:"2026-06"},
{id:"salesforce-bos", name:"Salesforce (Cambridge)", cat:"corporate", loc:"Cambridge", approx:true,
  lat:42.3656, lng:-71.0834, url:"https://salesforce.com",
  desc:"CRM leader with growing AI research presence in Cambridge. Einstein AI platform development and enterprise AI integration.",
  why:"AI research talent recruited from MIT/Harvard. Enterprise platform that many AI startups build on or sell through.",
  tags:["CRM","enterprise AI","platform"], links:[], lastVerified:"2026-06"},
{id:"apple-bos", name:"Apple (Cambridge)", cat:"corporate", loc:"Cambridge", approx:true,
  lat:42.3639, lng:-71.0929, url:"https://apple.com",
  desc:"On-device AI and ML research office. Focus on Siri, privacy-preserving machine learning, computer vision, and natural language processing.",
  why:"Recruits heavily from MIT/Harvard. On-device AI thesis is unique in the ecosystem — relevant for edge AI and privacy-focused founders.",
  tags:["on-device AI","privacy","ML research"], links:[], lastVerified:"2026-06"},
{id:"redhat-bos", name:"Red Hat (Boston)", cat:"corporate", loc:"100 East St, Boston",
  lat:42.3475, lng:-71.0509, url:"https://redhat.com",
  desc:"Open source enterprise leader. Boston headquarters with major AI (OpenShift AI, vLLM), hybrid cloud (OpenShift), and automation (Ansible) engineering teams.",
  why:"Co-sponsor of The Open Accelerator and MA AI Hub. Open source AI infrastructure (Podman, InstructLab, RamaLama) used by founders across the ecosystem.",
  tags:["open source","AI infrastructure","enterprise"], links:["toa","aihub"], lastVerified:"2026-06"},
// ---------- STARTUPS / AI COMPANIES ----------
{id:"liquid", name:"Liquid AI", cat:"startup", loc:"Kendall Sq, Cambridge", approx:true,
 lat:42.3640, lng:-71.0830, url:"https://www.liquid.ai", badge:"$250M+ raised",
 desc:"MIT CSAIL spinout building Liquid Foundation Models — small, efficient models for on-device and enterprise AI. Raised $250M led by AMD; partnered with Mercedes-Benz on in-car AI.",
 why:"Boston's foundation-model champion — proof you can build frontier AI here, not just in SF.",
 tags:["foundation models","edge AI"], stages:[], links:["csail"], lastVerified:"2026-06"},
{id:"suno", name:"Suno", cat:"startup", loc:"Cambridge", approx:true,
 lat:42.3653, lng:-71.1031, url:"https://suno.com", badge:"$5.4B valuation",
 desc:"AI music generation used by tens of millions. Raised $400M in June 2026 at a $5.4B valuation — one of the largest Massachusetts VC deals of the year.",
 why:"The breakout consumer AI story of the ecosystem; their team came from Kensho.",
 tags:["music","consumer AI"], stages:[], links:["kensho"], lastVerified:"2026-06"},
{id:"blitzy", name:"Blitzy", cat:"startup", loc:"Boston", approx:true,
 lat:42.3560, lng:-71.0570, url:"https://blitzy.com",
 desc:"Autonomous software development platform — among Massachusetts' most heavily funded AI startups.",
 why:"A homegrown bet on agentic coding at enterprise scale.",
 tags:["agents","devtools"], stages:[], lastVerified:"2026-06"},
{id:"datarobot", name:"DataRobot", cat:"startup", loc:"225 Franklin St, Boston",
 lat:42.3560, lng:-71.0545, url:"https://www.datarobot.com",
 desc:"Enterprise AI platform pioneer (founded 2012) — one of Boston's original machine-learning unicorns.",
 why:"Its alumni diaspora seeded a generation of Boston ML startups.",
 tags:["enterprise ML","unicorn"], stages:[], lastVerified:"2026-06"},
{id:"recfut", name:"Recorded Future", cat:"startup", loc:"Somerville", approx:true,
 lat:42.3920, lng:-71.1003, url:"https://www.recordedfuture.com", badge:"$2.65B exit",
 desc:"AI-powered threat intelligence, acquired by Mastercard for $2.65B (2024) — one of the region's biggest AI exits.",
 why:"Proof of deep exit appetite for Boston AI security companies.",
 tags:["security","exit"], stages:[], lastVerified:"2026-06"},
{id:"bdyn", name:"Boston Dynamics", cat:"startup", loc:"Waltham, MA", approx:true,
 lat:42.3765, lng:-71.2356, url:"https://bostondynamics.com",
 desc:"The world's most famous robotics company — an MIT spinout, now Hyundai-owned, increasingly AI-driven (Atlas, Spot, Stretch).",
 why:"The gravitational anchor of Boston's robotics-AI talent pool.",
 tags:["robotics","MIT spinout"], stages:[], links:["rai"], lastVerified:"2026-06"},
{id:"kensho", name:"Kensho", cat:"startup", loc:"Harvard Sq, Cambridge", approx:true,
 lat:42.3736, lng:-71.1190, url:"https://kensho.com", badge:"$550M exit",
 desc:"AI for financial intelligence; acquired by S&P Global for ~$550M — then its founders went on to start Suno.",
 why:"A case study in Boston's founder-recycling flywheel.",
 tags:["fintech","exit"], stages:[], links:["suno"], lastVerified:"2026-06"},
{id:"tamr", name:"Tamr", cat:"startup", loc:"Cambridge", approx:true,
 lat:42.3650, lng:-71.0800, url:"https://www.tamr.com",
 desc:"AI-native data mastering, co-founded by database legend Michael Stonebraker out of MIT CSAIL.",
 why:"Classic CSAIL-to-company playbook.",
 tags:["data","MIT spinout"], stages:[], links:["csail"], lastVerified:"2026-06"},
{id:"pathai", name:"PathAI", cat:"startup", loc:"Fenway, Boston", approx:true,
 lat:42.3450, lng:-71.1030, url:"https://www.pathai.com",
 desc:"AI-powered pathology for drug development and diagnostics.",
 why:"Flagship example of Boston's AI-meets-medicine advantage.",
 tags:["health","diagnostics"], stages:[], lastVerified:"2026-06"},
{id:"generate", name:"Generate:Biomedicines", cat:"startup", loc:"Somerville", approx:true,
 lat:42.3900, lng:-71.0830, url:"https://generatebiomedicines.com",
 desc:"Generative AI for protein therapeutics, created by Flagship Pioneering.",
 why:"Where generative AI and Boston biotech collide at scale.",
 tags:["biotech","generative"], stages:[], links:["flagship"], lastVerified:"2026-06"},
{id:"lila", name:"Lila Sciences", cat:"startup", loc:"Cambridge", approx:true,
 lat:42.3660, lng:-71.0760, url:"https://www.lila.ai",
 desc:"Flagship-founded venture building 'scientific superintelligence' — AI-run autonomous labs.",
 why:"One of the most ambitious AI-for-science bets anywhere.",
 tags:["AI for science"], stages:[], links:["flagship"], lastVerified:"2026-06"},
{id:"cogito", name:"Cogito", cat:"startup", loc:"Boston", approx:true,
 lat:42.3554, lng:-71.0560, url:"https://cogitocorp.com",
 desc:"Real-time conversational AI coaching, spun out of MIT Media Lab research.",
 why:"Long-running proof of emotion-AI in production.",
 tags:["voice","MIT spinout"], stages:[], links:["medialab"], lastVerified:"2026-06"},
{id:"realtime", name:"Realtime Robotics", cat:"startup", loc:"Fort Point, Boston", approx:true,
 lat:42.3470, lng:-71.0490, url:"https://rtr.ai",
 desc:"Motion planning for industrial robots at machine speed.",
 why:"Part of the dense Fort Point/Seaport robotics cluster.",
 tags:["robotics","industrial"], stages:[], lastVerified:"2026-06"},
{id:"righthand", name:"RightHand Robotics", cat:"startup", loc:"Somerville", approx:true,
 lat:42.3870, lng:-71.0990, url:"https://www.righthandrobotics.com",
 desc:"AI-driven robotic picking for e-commerce fulfillment, with Harvard/MIT research roots.",
 why:"Warehouse AI born from Boston lab benches.",
 tags:["robotics","logistics"], stages:[], lastVerified:"2026-06"},
{id:"pickle", name:"Pickle Robot", cat:"startup", loc:"Charlestown, Boston", approx:true,
 lat:42.3780, lng:-71.0650, url:"https://www.picklerobot.com",
 desc:"Robots that unload trucks — physical AI for the supply chain.",
 why:"Embodied-AI startup thriving outside the Kendall bubble.",
 tags:["robotics","logistics"], stages:[], lastVerified:"2026-06"},
{id:"concertai", name:"ConcertAI", cat:"startup", loc:"Cambridge", approx:true,
 lat:42.3630, lng:-71.0850, url:"https://www.concertai.com",
 desc:"AI and real-world data for oncology research and care.",
 why:"Health-data AI at unicorn scale, headquartered in Cambridge.",
 tags:["health","oncology"], stages:[], lastVerified:"2026-06"},

// ---------- VENTURE CAPITAL ----------
{id:"venx", name:"Ven^X", cat:"vc", loc:"125 High St, Boston",
 lat:42.3553, lng:-71.0541, url:"https://www.venx.vc",
 desc:"Boston's first collaborative deep-tech VC hub, where venture investors co-locate downtown to share knowledge, work with portfolio companies, and syndicate deals in deep tech and AI.",
 why:"For founders in hard deep-tech/AI problem spaces, it concentrates investors who already understand the domain and pool resources to syndicate larger checks.",
 tags:["deep tech","syndication"], stages:[4], links:[], lastVerified:"2026-06"},
{id:"epipelagic", name:"Epipelagic Ventures", cat:"vc", loc:"1 Broadway, Cambridge",
 lat:42.3626, lng:-71.0843, url:"https://www.epipelagic.vc",
 desc:"A founder-first venture studio in Kendall Square that surrounds early-stage startups with capital, mentorship and hands-on operational support to reach their next milestone.",
 why:"A hands-on venture-studio model for pre-seed founders — especially edtech, consumer, health and wellness, or moonshot ideas — pairing funding with active build support.",
 tags:["venture studio","early stage"], stages:[3,4], links:[], lastVerified:"2026-06"},
{id:"nextview", name:"NextView Ventures", cat:"vc", loc:"Boston, Seaport", approx:true,
  lat:42.3519, lng:-71.0444, url:"https://nextview.vc",
  desc:"Seed-stage fund focused on 'redesigning the everyday economy' — backing founders using software and AI to solve mass-market problems.",
  why:"Boston-native since 2010. Writes $500K–$2M checks at seed. Notable exit: Hatch acquired by Yelp for $300M (2026).",
  tags:["seed","consumer","everyday economy"], stages:[3,4], lastVerified:"2026-06"},
{id:"rough-draft", name:"Rough Draft Ventures", cat:"vc", loc:"Cambridge", approx:true,
  lat:42.3656, lng:-71.1009, url:"https://roughdraft.vc",
  desc:"General Catalyst's student-focused venture arm — invests exclusively in student and recent-graduate founders.",
  why:"The earliest entry point for MIT/Harvard AI founders. $25K–$100K checks. Critical pipeline for academic spinouts before they're on anyone else's radar.",
  tags:["student","pre-seed","academic"], stages:[1,2,3], lastVerified:"2026-06"},
{id:"matrix", name:"Matrix Partners", cat:"vc", loc:"Bay Colony, Waltham",
  lat:42.3895, lng:-71.2265, url:"https://www.matrixpartners.com",
  desc:"Early-stage VC with deep Boston roots — among the region's most established firms for seed and Series A.",
  why:"Led early rounds in HubSpot, Ocient, CloudBees. Strong thesis in SaaS, infrastructure, and applied AI.",
  tags:["early-stage","SaaS","infrastructure"], stages:[4,5], lastVerified:"2026-06"},
{id:"lux", name:"Lux Capital", cat:"vc", loc:"Boston (satellite)", approx:true,
  lat:42.3601, lng:-71.0589, url:"https://luxcapital.com",
  desc:"Deep tech venture firm investing in AI, biotech, energy, and frontier science. NYC HQ with active Boston dealflow.",
  why:"Invests in technically ambitious founders — the kind Boston produces. Notable: Kensho (acquired by S&P Global). Regularly co-invests with local firms.",
  tags:["deep tech","frontier","AI"], stages:[4,5], lastVerified:"2026-06"},
{id:"ibm-ventures", name:"IBM Ventures", cat:"vc", loc:"Cambridge, Kendall Sq", approx:true,
  lat:42.3625, lng:-71.0843, url:"https://www.ibm.com/ventures",
  desc:"IBM's strategic investment arm — invests in AI, hybrid cloud, quantum, and enterprise tech startups.",
  why:"Co-sponsor of The Open Accelerator. Strategic investor that brings enterprise distribution, not just capital. Particularly valuable for startups selling to regulated industries.",
  tags:["strategic","enterprise","hybrid cloud"], stages:[4,5], links:["toa"], lastVerified:"2026-06"},
{id:"gc", name:"General Catalyst", cat:"vc", loc:"20 University Rd, Cambridge",
 lat:42.3722, lng:-71.1183, url:"https://www.generalcatalyst.com",
 desc:"Global venture firm with deep Cambridge roots — among the most active AI investors anywhere.",
 why:"Seed through growth; their healthcare-AI and applied-AI theses fit Boston founders.",
 tags:["multi-stage","global"], stages:[4,5], lastVerified:"2026-06"},
{id:"glasswing", name:"Glasswing Ventures", cat:"vc", loc:"Boston", approx:true,
 lat:42.3554, lng:-71.0530, url:"https://glasswing.vc",
 desc:"Seed firm investing exclusively in AI-native enterprise and security startups.",
 why:"They literally publish an AI landscape map — and built their thesis around Boston's technical talent.",
 tags:["AI-native","seed"], stages:[4], lastVerified:"2026-06"},
{id:"pillar", name:"Pillar VC", cat:"vc", loc:"Fort Point, Boston", approx:true,
 lat:42.3490, lng:-71.0480, url:"https://www.pillar.vc",
 desc:"Founder-friendly seed firm; runs free programs for PhD founders (Pillar Frequency) across AI and bio.",
 why:"Among the most accessible institutional seed money for first-time technical founders.",
 tags:["seed","PhD founders"], stages:[2,4], lastVerified:"2026-06"},
{id:"hyperplane", name:"Hyperplane", cat:"vc", loc:"Fort Point, Boston", approx:true,
 lat:42.3500, lng:-71.0470, url:"https://www.hyperplane.vc",
 desc:"Seed fund backing machine-intelligence companies since before it was cool.",
 why:"Technical partners who actually read your model card.",
 tags:["seed","ML"], stages:[4], lastVerified:"2026-06"},
{id:"flybridge", name:"Flybridge", cat:"vc", loc:"Back Bay, Boston", approx:true,
 lat:42.3510, lng:-71.0720, url:"https://www.flybridge.com",
 desc:"Seed firm with an explicit AI-first thesis and long Boston history.",
 why:"Publishes practical AI-startup playbooks; strong community programs.",
 tags:["seed","AI-first"], stages:[4], lastVerified:"2026-06"},
{id:"underscore", name:"Underscore VC", cat:"vc", loc:"Downtown Boston", approx:true,
 lat:42.3580, lng:-71.0570, url:"https://underscore.vc",
 desc:"Boston seed firm with a community-driven model (Core) connecting founders to operators.",
 why:"Their operator network doubles as a free advisory bench.",
 tags:["seed","B2B"], stages:[2,4], lastVerified:"2026-06"},
{id:"fc", name:"Founder Collective", cat:"vc", loc:"Harvard Sq, Cambridge", approx:true,
 lat:42.3744, lng:-71.1200, url:"https://www.foundercollective.com",
 desc:"Seed fund built by founders, famously aligned with keeping founders in control.",
 why:"Backed Uber, Coupang — and writes great essays on capital efficiency.",
 tags:["seed","founder-led"], stages:[4], lastVerified:"2026-06"},
{id:"battery", name:"Battery Ventures", cat:"vc", loc:"One Marina Park Dr, Seaport",
 lat:42.3535, lng:-71.0440, url:"https://www.battery.com",
 desc:"Global multi-stage firm headquartered on Fan Pier with active AI/infra practice.",
 why:"Growth capital without leaving the Seaport.",
 tags:["multi-stage","infra"], stages:[5], lastVerified:"2026-06"},
{id:"bessemer", name:"Bessemer Venture Partners (Boston)", cat:"vc", loc:"Back Bay, Boston", approx:true,
 lat:42.3496, lng:-71.0760, url:"https://www.bvp.com",
 desc:"One of the oldest VC firms in the world, with a significant Boston presence and AI roadmaps.",
 why:"Their public 'State of AI' roadmaps tell you exactly what they want to fund.",
 tags:["multi-stage"], stages:[4,5], lastVerified:"2026-06"},
{id:"flagship", name:"Flagship Pioneering", cat:"vc", loc:"55 Cambridge Pkwy, Cambridge",
 lat:42.3654, lng:-71.0762, url:"https://www.flagshippioneering.com",
 desc:"Venture creation engine (Moderna's maker) now founding AI-for-science companies like Generate and Lila.",
 why:"They don't fund companies — they build them. A unique path for scientist-founders.",
 tags:["venture creation","bio+AI"], stages:[4,5], links:["generate","lila"], lastVerified:"2026-06"},
{id:"atlas", name:"Atlas Venture", cat:"vc", loc:"300 Technology Sq, Cambridge",
 lat:42.3633, lng:-71.0930, url:"https://www.atlasventure.com",
 desc:"Premier early-stage biotech VC increasingly backing AI-enabled drug discovery.",
 why:"The bridge between Boston's two superpowers: AI and biotech.",
 tags:["biotech","seed"], stages:[4], lastVerified:"2026-06"},
{id:"polaris", name:"Polaris Partners", cat:"vc", loc:"Seaport, Boston", approx:true,
 lat:42.3530, lng:-71.0450, url:"https://www.polarispartners.com",
 desc:"Long-standing Boston firm investing across healthcare and technology.",
 why:"Decades of pattern recognition on Boston founders.",
 tags:["healthcare","tech"], stages:[4,5], lastVerified:"2026-06"},
{id:"engine-v", name:"Engine Ventures", cat:"vc", loc:"750 Main St, Cambridge",
 lat:42.3638, lng:-71.0975, url:"https://engineventures.com",
 desc:"The MIT-spun fund investing in 'tough tech' — fusion, robotics, AI for the physical world.",
 why:"Patient capital for science-heavy AI that SaaS funds won't touch.",
 tags:["tough tech","deep tech"], stages:[4,5], links:["engine"], lastVerified:"2026-06"},
{id:"e14", name:"E14 Fund", cat:"vc", loc:"Kendall Sq, Cambridge", approx:true,
 lat:42.3608, lng:-71.0868, url:"https://www.e14fund.com",
 desc:"The MIT Media Lab-affiliated fund backing MIT-connected founders at the earliest stages.",
 why:"If you're MIT-affiliated, they should be your first coffee.",
 tags:["pre-seed","MIT"], stages:[4], links:["medialab"], lastVerified:"2026-06"},
{id:"converge", name:"Converge", cat:"vc", loc:"Boston", approx:true,
 lat:42.3600, lng:-71.0580, url:"https://www.convergevp.com",
 desc:"Seed firm focused on AI and data startups emerging from Boston's academic ecosystem.",
 why:"Purpose-built for exactly the founder this atlas serves.",
 tags:["seed","AI/data"], stages:[4], lastVerified:"2026-06"},
{id:"accomplice", name:"Accomplice", cat:"vc", loc:"Cambridge", approx:true,
 lat:42.3736, lng:-71.1210, url:"https://www.accomplice.co",
 desc:"Community-driven seed firm (Boston roots of Atlas Venture's tech practice); behind BOSS and other ecosystem efforts.",
 why:"Long history of seeding Boston's startup community itself.",
 tags:["seed","community"], stages:[4], lastVerified:"2026-06"},
{id:"406", name:".406 Ventures", cat:"vc", loc:"470 Atlantic Ave, Boston",
 lat:42.354189399999996, lng:-71.0513553, url:"https://www.406ventures.com",
 desc:"Early-stage firm strong in cybersecurity, healthcare IT and data/AI.",
 why:"Security-AI founders: they wrote the local playbook.",
 tags:["security","seed"], stages:[4], lastVerified:"2026-06"},
{id:"material", name:"Material Impact", cat:"vc", loc:"Boston", approx:true,
 lat:42.3556, lng:-71.0560, url:"https://www.materialimpact.com",
 desc:"Deep-tech fund turning material science and embodied-AI breakthroughs into companies.",
 why:"For AI that ships with atoms, not just bits.",
 tags:["deep tech"], stages:[4], lastVerified:"2026-06"},
{id:"massventures", name:"MassVentures", cat:"vc", loc:"Charlestown, Boston", approx:true,
 lat:42.3782, lng:-71.0640, url:"https://www.mass-ventures.com",
 desc:"The Commonwealth's own venture arm — START grants and early capital for MA deep-tech startups.",
 why:"Non-dilutive START grants (up to $500K) for SBIR-funded companies. Free money, seriously.",
 tags:["state fund","grants"], stages:[3,4], links:["aihub"], lastVerified:"2026-06"},
{id:"foundersedge", name:"FoundersEdge", cat:"vc", loc:"100 Summer St, Boston", approx:true,
 lat:42.3538, lng:-71.0574, url:"https://www.foundersedge.com",
 desc:"Pre-seed fund writing $100–$200K first checks into AI-native, software-first B2B startups, run by post-exit operators Greg Raiz (Raizlabs, Techstars Boston) and Jess Lynch (Wishroute).",
 why:"Operator GPs who lead or co-invest without taking a board seat, plus a CEO peer cohort and open demo nights like Ditch the Deck — first-check money that comes with hands-on company.",
 tags:["pre-seed","B2B SaaS","AI-native"], stages:[2,4], lastVerified:"2026-08"},
{id:"milemark", name:"Milemark Capital", cat:"vc", loc:"303 Third St, Cambridge",
 lat:42.3643, lng:-71.0840, url:"https://www.milemark.capital",
 desc:"Kendall Square firm founded in 2022 investing pre-seed and seed in startups differentiated by proprietary AI systems, models and data; founding partners include MIT Sloan's Sinan Aral.",
 why:"Backing diverse founding teams is the explicit thesis, the MIT connection is real, and the portfolio already lists 17+ applied-AI companies — a natural first-round conversation in Kendall's orbit.",
 tags:["pre-seed","seed","applied AI"], stages:[4], lastVerified:"2026-08"},
{id:"cybernetix", name:"Cybernetix Ventures", cat:"vc", loc:"125 High St, Boston",
 lat:42.3553, lng:-71.0541, url:"https://cybernetix.vc",
 desc:"Boston fund investing exclusively in robotics, automation and physical AI at pre-seed through Series A; raising a $100M Fund II after 23 Fund I investments.",
 why:"Purpose-built for robotics and physical-AI founders — checks from robotics operators, plus the annual Robotics Invest event that gathers the sector's investors downtown.",
 tags:["robotics","physical AI"], stages:[4], lastVerified:"2026-08"},
{id:"two-lanterns", name:"Two Lanterns Venture Partners", cat:"vc", loc:"Newton Centre", approx:true,
 lat:42.3350, lng:-71.1915, url:"https://www.2l.vc",
 desc:"Pre-seed and seed fund backing AI-native and AI-empowered startups across the US and Israel, founded by MassChallenge founder John Harthorne.",
 why:"First checks from the founder of MassChallenge, written explicitly for AI-native companies — one of the few area funds whose entire thesis is early AI.",
 tags:["pre-seed","AI-native"], stages:[4], lastVerified:"2026-08"},
{id:"innospark", name:"Innospark Ventures", cat:"vc", loc:"31 St James Ave, Boston", approx:true,
 lat:42.3509, lng:-71.0718, url:"https://innospark.vc",
 desc:"Boston seed fund investing only where AI is the core product — applied AI and deep tech across healthcare, life sciences and enterprise; checks typically $1M–$3M.",
 why:"Run by a repeat AI founder and backs nothing but AI companies — as on-thesis as Boston seed money gets.",
 tags:["applied AI","seed"], stages:[4], lastVerified:"2026-08"},
{id:"first-star", name:"First Star Ventures", cat:"vc", loc:"245 Main St, Cambridge",
 lat:42.3625, lng:-71.0847, url:"https://firststar.vc",
 desc:"Cambridge pre-seed fund writing $100K–$1M first checks into AI, robotics and frontier-computing companies; both partners are technical ex-founders.",
 why:"First-check money from two GPs who can read your research — they show up before anyone else does.",
 tags:["pre-seed","frontier tech"], stages:[4], lastVerified:"2026-08"},
{id:"link-ventures", name:"Link Ventures", cat:"vc", loc:"One Kendall Sq, Cambridge",
 lat:42.3667, lng:-71.0908, url:"https://www.linkventures.com",
 desc:"Kendall Square fund backing technical AI founders from MIT, Harvard and beyond — leads pre-seed through Series A and incubates companies in its 40,000 sq ft Link Studio.",
 why:"AI-first capital that comes with space, compute and back-office support in the middle of Kendall Square.",
 tags:["AI-first","incubator"], stages:[3,4], lastVerified:"2026-08"},
{id:"hubspot-v", name:"HubSpot Ventures", cat:"vc", loc:"2 Canal Park, Cambridge",
 lat:42.3701, lng:-71.0763, url:"https://www.hubspot.com/ventures",
 desc:"HubSpot's strategic venture arm — $500K–$5M checks from seed through Series B, focused on AI & agent development and intelligent apps for SMBs; investments include Lovable and ElevenLabs.",
 why:"Strategic capital with distribution: the HubSpot platform and its SMB customer base come with the check.",
 tags:["strategic","AI agents"], stages:[4,5], lastVerified:"2026-08"},
{id:"spark-capital", name:"Spark Capital", cat:"vc", loc:"200 Clarendon St, Boston",
 lat:42.3492, lng:-71.0751, url:"https://www.sparkcapital.com",
 desc:"Multi-stage firm founded in Boston in 2005, investing seed through growth across consumer, enterprise and AI — led Anthropic's Series C.",
 why:"A Boston-rooted firm that has led a frontier-AI-lab round — credibility that matters when you're raising for ambitious AI.",
 tags:["multi-stage","AI"], stages:[4,5], links:["anthropic-bos"], lastVerified:"2026-08"},
{id:"bcv", name:"Bain Capital Ventures", cat:"vc", loc:"200 Clarendon St, Boston",
 lat:42.3492, lng:-71.0751, url:"https://www.baincapitalventures.com",
 desc:"Boston-founded multi-stage firm with named AI-apps and AI-infrastructure practices — $1–5M seed checks through $100M growth rounds, plus the BCV Labs AI incubator.",
 why:"Seed through growth without leaving the cap table, and an AI incubator on top.",
 tags:["multi-stage","AI infrastructure"], stages:[4,5], lastVerified:"2026-08"},
{id:"gv", name:"GV (Google Ventures)", cat:"vc", loc:"355 Main St, Cambridge",
 lat:42.3627, lng:-71.0878, url:"https://www.gv.com",
 desc:"Alphabet's venture arm, with a Kendall Square office co-located with Google — multi-stage across AI, healthcare and life sciences, with 50+ AI-native application companies backed.",
 why:"A local door into one of the most active AI investors anywhere — especially strong for healthcare-AI founders.",
 tags:["multi-stage","healthcare AI"], stages:[4,5], links:["google"], lastVerified:"2026-08"},
{id:"unusual", name:"Unusual Ventures", cat:"vc", loc:"341 Newbury St, Boston",
 lat:42.3487, lng:-71.0869, url:"https://www.unusual.vc",
 desc:"Seed-only enterprise software firm with a Boston office on Newbury Street — hands-on, operator-led support for technical founders; recent AI seeds include Fal and Resolve AI.",
 why:"Seed specialists who do the unglamorous go-to-market work with you — one of the few Bay Area seed brands with a real Boston base.",
 tags:["seed","enterprise"], stages:[4], lastVerified:"2026-08"},
{id:"venture-guides", name:"Venture Guides", cat:"vc", loc:"100 Causeway St, Boston",
 lat:42.3656, lng:-71.0614, url:"https://www.ventureguides.com",
 desc:"Boston operator-led fund investing pre-seed through Series A in infrastructure software — cloud infrastructure, security, AI and data; closed a $262.5M Fund II in 2025.",
 why:"Operators from the Turbonomic lineage writing early checks specifically for infrastructure founders — a natural fit if you're building AI infra.",
 tags:["infrastructure","pre-seed"], stages:[4], lastVerified:"2026-08"},
{id:"j2", name:"J2 Ventures", cat:"vc", loc:"Boston (downtown)", approx:true,
 lat:42.3597, lng:-71.0566, url:"https://j2vp.com",
 desc:"Boston early-stage firm investing in dual-use technologies — advanced computing, cybersecurity, AI and biomedical tools serving both national-security and commercial markets; closed the $250M Brookhaven Fund in 2024.",
 why:"The natural first call if your AI serves both commercial and defense markets — their portfolio averages $2 of non-dilutive government funding for every $1 invested.",
 tags:["dual-use","defense"], stages:[4], lastVerified:"2026-08"},
{id:"suffolk-tech", name:"Suffolk Technologies", cat:"vc", loc:"65 Allerton St, Boston",
 lat:42.3281, lng:-71.0697, url:"https://suffolktech.com",
 desc:"Venture platform of Suffolk Construction investing pre-seed through growth in built-environment technology — ConTech, PropTech and infrastructure, with a strong AI tilt; runs the BOOST accelerator.",
 why:"The go-to investor for AI founders building for construction and the built world — with Suffolk Construction as a built-in pilot customer.",
 tags:["contech","built world"], stages:[4,5], lastVerified:"2026-08"},
{id:"january", name:"January Ventures", cat:"vc", loc:"Boston (Back Bay)", approx:true,
 lat:42.3496, lng:-71.0746, url:"https://www.january.ventures",
 desc:"Woman-led pre-seed fund writing $150K–$750K checks before product, customers or revenue — currently focused on founders transforming healthcare, manufacturing and supply chain with AI.",
 why:"True pre-seed money with an explicit thesis on AI founders from non-traditional backgrounds — they invest earlier than almost anyone.",
 tags:["pre-seed","diverse founders"], stages:[4], lastVerified:"2026-08"},
{id:"companyon", name:"Companyon Ventures", cat:"vc", loc:"184 High St, Boston",
 lat:42.3566, lng:-71.0528, url:"https://companyon.vc",
 desc:"Boston expansion-stage fund leading post-seed rounds for B2B AI and software startups — just four investments a year, with hands-on go-to-market and recruiting support.",
 why:"Specialists in the awkward round between seed and Series A — useful exactly when traction is real but not yet Series-A-shaped.",
 tags:["post-seed","B2B SaaS"], stages:[4], lastVerified:"2026-08"},
{id:"xfund", name:"Xfund", cat:"vc", loc:"67 Mount Auburn St, Cambridge",
 lat:42.3718, lng:-71.1183, url:"https://www.xfund.com",
 desc:"Seed fund purpose-built for research-university founders, with offices in Harvard Square and Palo Alto; recent investments lean heavily AI.",
 why:"If you're spinning a company out of a Harvard or MIT lab, their Harvard Square office is one of the most natural first stops.",
 tags:["university spinouts","seed"], stages:[4], lastVerified:"2026-08"},
{id:"boston-seed", name:"Boston Seed Capital", cat:"vc", loc:"Wellesley Hills", approx:true,
 lat:42.3255, lng:-71.2538, url:"https://bostonseed.com",
 desc:"One of Boston's first institutional seed funds (2010), investing pre-seed and seed with artificial intelligence now a named expertise area alongside consumer and B2B SaaS.",
 why:"Long-running first-check money in the western suburbs — a fit for consumer- and SaaS-flavored AI founders.",
 tags:["pre-seed","seed"], stages:[4], lastVerified:"2026-08"},
{id:"fprime", name:"F-Prime Capital", cat:"vc", loc:"1 Main St, Cambridge",
 lat:42.3622, lng:-71.0800, url:"https://www.fprimecapital.com",
 desc:"Fidelity-rooted Kendall Square firm investing from seed through growth across life sciences, healthcare, tech and fintech — one of the region's highest-volume seed and Series A leads.",
 why:"Especially relevant for AI founders in healthcare, life sciences and fintech, where its scientist-operator bench runs deepest.",
 tags:["multi-stage","healthcare AI"], stages:[4,5], lastVerified:"2026-08"},
{id:"lama", name:"Lama Partners", cat:"vc", loc:"131 Dartmouth St, Boston", approx:true,
 lat:42.3471, lng:-71.0760, url:"https://www.lama.vc",
 desc:"A $50M seed fund and venture studio operating from Boston and Tel Aviv, backing AI-native cybersecurity and IT-infrastructure companies from inception.",
 why:"Purpose-built for cybersecurity-and-AI founders, with LPs drawn from partners at Insight, Battery, Bessemer and CRV.",
 tags:["cybersecurity","AI-native"], stages:[4], lastVerified:"2026-08"},
{id:"sbxi", name:"SBXi", cat:"vc", loc:"Kendall Sq, Cambridge", approx:true,
 lat:42.3601, lng:-71.0900, url:"https://www.sbxi.com",
 desc:"Sponsor-backed syndicate writing fast first checks exclusively for MIT-alumni founders — $10K–$100K on SAFEs, up to $1M matching a qualifying term sheet; grew out of the MIT Sandbox program.",
 why:"One of the quickest paths to a first yes for the large MIT-born share of Boston AI startups.",
 tags:["MIT founders","first check"], stages:[4], lastVerified:"2026-08"},
{id:"bosch-v", name:"Bosch Ventures", cat:"vc", loc:"Cambridge", approx:true,
 lat:42.3650, lng:-71.0850, url:"https://bosch.ventures",
 desc:"Robert Bosch's corporate venture arm, whose Boston-area office anchors its North American enterprise-AI investing — a $270M sixth fund writing $5M–$10M checks, with local investments including Blitzy.",
 why:"Strategic capital plus a route to industrial customers — strongest for AI applied to the physical world.",
 tags:["strategic","industrial AI"], stages:[4,5], links:["blitzy"], lastVerified:"2026-08"},

// ---------- ANGEL GROUPS ----------
{id:"bha", name:"Boston Harbor Angels", cat:"angel", loc:"Boston (meets downtown)", approx:true,
 lat:42.3565, lng:-71.0550, url:"https://www.bostonharborangels.com",
 desc:"One of Boston's most active angel groups, investing across tech and life sciences.",
 why:"Monthly pitch meetings — a classic first-check source.",
 tags:["angels","pitch nights"], stages:[2,4], lastVerified:"2026-06"},
{id:"hub-angels", name:"Hub Angels", cat:"angel", loc:"Boston", approx:true,
 lat:42.3545, lng:-71.0600, url:"https://www.hubangels.com",
 desc:"Long-running Boston angel fund investing in early-stage tech.",
 why:"Fund structure means faster, cleaner closes than loose syndicates.",
 tags:["angels"], stages:[4], lastVerified:"2026-06"},
{id:"mit-angels", name:"MIT Angels", cat:"angel", loc:"Cambridge", approx:true,
 lat:42.3620, lng:-71.0870, url:"https://www.mitangels.org",
 desc:"Angel network of MIT alumni backing MIT-connected founders.",
 why:"Warmest possible audience for an MIT-affiliated pitch.",
 tags:["angels","MIT"], stages:[4], lastVerified:"2026-06"},
{id:"tie", name:"TiE Boston Angels", cat:"angel", loc:"Cambridge", approx:true,
 lat:42.3650, lng:-71.0900, url:"https://boston.tie.org",
 desc:"Angel arm of TiE Boston, one of the region's largest entrepreneur networks.",
 why:"Mentorship + capital + a giant founder community in one membership.",
 tags:["angels","mentorship"], stages:[2,4], lastVerified:"2026-06"},
{id:"walnut", name:"Walnut Venture Associates", cat:"angel", loc:"Boston area", approx:true,
 lat:42.3500, lng:-71.0700, url:"https://www.walnutventures.com",
 desc:"Veteran angel group of exited founders and operators.",
 why:"Angels who have run companies — diligence doubles as advice.",
 tags:["angels"], stages:[4], lastVerified:"2026-06"},
{id:"launchpad", name:"LaunchPad Venture Group", cat:"angel", loc:"Newton, MA", approx:true,
 lat:42.3370, lng:-71.2092, url:"https://launchpadventuregroup.com",
 desc:"One of the largest angel groups in the Northeast.",
 why:"Syndicates with other groups — one yes can multiply.",
 tags:["angels"], stages:[4], lastVerified:"2026-06"},
{id:"hbsaa", name:"HBS Alumni Angels of Boston", cat:"angel", loc:"Allston, Boston", approx:true,
 lat:42.3660, lng:-71.1230, url:"https://www.hbsalumniangels.com",
 desc:"Angel network of Harvard Business School alumni.",
 why:"Capital plus the HBS operator rolodex.",
 tags:["angels","Harvard"], stages:[4], lastVerified:"2026-06"},

// ---------- ACCELERATORS & FOUNDER SUPPORT ----------
{id:"deltav", name:"MIT delta v", cat:"accel", loc:"1 Amherst St, Cambridge (Trust Center)",
 lat:42.3601, lng:-71.0852, url:"https://entrepreneurship.mit.edu/accelerator/",
 desc:"MIT's summer venture accelerator: up to $20K equity-free plus living stipends, ending in a famous September Demo Day.",
 why:"The single best on-ramp for MIT student founders. Zero dilution.",
 tags:["equity-free","students"], stages:[3,4], links:["trust","deltav-demo"], lastVerified:"2026-06"},
{id:"trust", name:"Martin Trust Center for MIT Entrepreneurship", cat:"accel", loc:"1 Amherst St, Cambridge",
 lat:42.3604, lng:-71.0848, url:"https://entrepreneurship.mit.edu",
 desc:"MIT's entrepreneurship home: courses, coaching, maker funds and the machinery behind delta v.",
 why:"Open-door entrepreneurship help if you're MIT-connected; their 'Disciplined Entrepreneurship' method is free for everyone.",
 tags:["mentorship","education"], stages:[1,2], links:["deltav"], lastVerified:"2026-06"},
{id:"vms", name:"MIT Venture Mentoring Service", cat:"accel", loc:"Cambridge (MIT campus)", approx:true,
 lat:42.3612, lng:-71.0920, url:"https://vms.mit.edu",
 desc:"Free, team-based mentoring from vetted entrepreneurs and executives for MIT-affiliated ventures. No equity, ever.",
 why:"Arguably the most underrated free resource in the ecosystem.",
 tags:["free","mentorship"], stages:[2], lastVerified:"2026-06"},
{id:"ilab", name:"Harvard Innovation Labs", cat:"accel", loc:"125 Western Ave, Allston",
 lat:42.3637, lng:-71.1252, url:"https://innovationlabs.harvard.edu",
 desc:"Harvard's venture launchpad — programming, space and the Venture Program for student and alumni founders.",
 why:"Free for Harvard affiliates and the President's Innovation Challenge awards $500K+ yearly.",
 tags:["students","equity-free"], stages:[2,3,4], links:["kempner"], lastVerified:"2026-06"},
{id:"engine", name:"The Engine", cat:"accel", loc:"750 Main St, Cambridge",
 lat:42.3636, lng:-71.0973, url:"https://engine.xyz",
 desc:"MIT-born tough-tech hub: 200,000 sq ft of labs, fabrication and offices plus a residency program for science-heavy startups.",
 why:"Lab space and equipment that would otherwise cost millions — built for AI that meets hardware, energy, or bio.",
 tags:["lab space","tough tech"], stages:[3], links:["engine-v"], lastVerified:"2026-06"},
{id:"techstars", name:"Techstars Boston", cat:"accel", loc:"Boston", approx:true,
 lat:42.3510, lng:-71.0450, url:"https://www.techstars.com",
 desc:"The storied global accelerator's Boston program — $120K for 6%, mentor-driven.",
 why:"The classic accelerator brand with a deep Boston mentor bench. (Verify current cohort status on their site.)",
 tags:["accelerator","$120K"], stages:[4], lastVerified:"2026-06"},
{id:"masschallenge", name:"MassChallenge", cat:"accel", loc:"Seaport, Boston", approx:true,
 lat:42.3496, lng:-71.0440, url:"https://masschallenge.org",
 desc:"Zero-equity global accelerator headquartered in Boston, awarding up to $1M in non-dilutive prizes per cohort.",
 why:"Free money and a massive partner network. Apply every year you're eligible.",
 tags:["equity-free","prizes"], stages:[3,4], lastVerified:"2026-06"},
{id:"massrobotics", name:"MassRobotics", cat:"accel", loc:"12 Channel St, Seaport",
 lat:42.3450, lng:-71.0454, url:"https://www.massrobotics.org",
 desc:"The world's largest independent robotics innovation hub: shared labs, test space and corporate partners for robotics & physical-AI startups.",
 why:"Embodied-AI founders get equipment, space and intros that nowhere else in the US concentrates this densely.",
 tags:["robotics","lab space"], stages:[3], lastVerified:"2026-06"},
{id:"greentown", name:"Greentown Labs", cat:"accel", loc:"444 Somerville Ave, Somerville",
 lat:42.3818, lng:-71.1057, url:"https://greentownlabs.com",
 desc:"North America's largest climatetech incubator — increasingly home to AI-for-energy and AI-for-climate startups.",
 why:"If your AI serves climate or energy, this is your tribe (and your lab bench).",
 tags:["climate","incubator"], stages:[3], lastVerified:"2026-06"},
{id:"toa", name:"The Open Accelerator (TOA)", cat:"accel", loc:"300 A St, Fort Point, Boston",
 lat:42.3486, lng:-71.0502, url:"https://the-open-accelerator.com", badge:"Applications open",
 desc:"Boston's open-source AI innovation hub — an initiative between the MA AI Hub, Red Hat and IBM Ventures, launched at Boston Tech Week 2026. Runs a founder residency (workspace, mentorship, GPU access), a community membership program, and a hands-on hackathon series.",
 why:"Purpose-built to close the enterprise-readiness gap: open-source architecture guidance, enterprise networks, and Google for Startups Cloud resources — designed for exactly the founders this atlas serves.",
 tags:["residency","open source","hackathons","GPU access"], stages:[1,2,3,4,5], links:["aihub","sundai","techweek"], lastVerified:"2026-06"},
{id:"xlr8", name:"XLR8 by Raiz Capital", cat:"accel", loc:"Downtown Boston", approx:true,
 lat:42.3560, lng:-71.0600, url:"https://www.raizcapital.com",
 desc:"Accelerator and early capital from Raiz Capital's downtown innovation campus.",
 why:"Accelerator + angel capital + co-working under one roof.",
 tags:["accelerator"], stages:[4], lastVerified:"2026-06"},
{id:"ssc", name:"SSC Venture Partners", cat:"accel", loc:"Boston College, Chestnut Hill",
 lat:42.3355, lng:-71.1685, url:"https://www.sscvp.com",
 desc:"Accelerator + fund for the Boston College founder community.",
 why:"BC's answer to delta v — equity-free summer program plus alumni capital.",
 tags:["students","BC"], stages:[3,4], lastVerified:"2026-06"},
{id:"idea-neu", name:"IDEA (Northeastern)", cat:"accel", loc:"Northeastern, Boston", approx:true,
 lat:42.3398, lng:-71.0892, url:"https://www.northeastern.edu/idea/",
 desc:"Northeastern's student-led venture accelerator with gap funding up to $10K.",
 why:"Equity-free gap funding and coaching, run by students for students.",
 tags:["students","equity-free"], stages:[2,3], lastVerified:"2026-06"},
{id:"c10", name:"C10 Labs", cat:"accel", loc:"CIC, 1 Broadway, Cambridge", approx:true,
 lat:42.3626, lng:-71.0842, url:"https://www.c10labs.com",
 desc:"AI-native venture studio and fund at CIC in Kendall Square — invests pre-seed to Series A and co-builds applied-AI companies; runs the AI BioHub with LabCentral and a Dimensional AI Hub with CIC.",
 why:"A venture-studio path: trade some ownership for hands-on company building, with dedicated tracks for AI-in-bio and enterprise AI.",
 tags:["venture studio","applied AI"], stages:[2,3,4], links:["cic","ai-biohub"], lastVerified:"2026-08"},
{id:"founder-institute", name:"Founder Institute Boston", cat:"accel", loc:"Boston", approx:true,
  lat:42.3554, lng:-71.0620, url:"https://fi.co/s/boston",
  desc:"Global pre-seed accelerator's Boston chapter. 4-month program for idea-stage to early-traction founders. Low equity model (3.5%).",
  why:"Lowest barrier to entry of any structured program. Strong alumni network. Good first step for founders who aren't yet ready for Techstars or MassChallenge.",
  tags:["pre-seed","idea-stage","low equity"], stages:[1,2], lastVerified:"2026-06"},

{id:"learnlaunch", name:"LearnLaunch Accelerator", cat:"accel", loc:"Boston, Back Bay", approx:true,
  lat:42.3489, lng:-71.0785, url:"https://learnlaunch.com",
  desc:"EdTech-focused accelerator supporting startups building AI-powered tools for education and workforce development.",
  why:"The definitive EdTech accelerator in the Northeast. Strong connections to K-12 districts, higher ed institutions, and workforce development organizations.",
  tags:["edtech","workforce","education"], stages:[3,4], lastVerified:"2026-06"},

{id:"pharmstars", name:"PharmStars", cat:"accel", loc:"Boston", approx:true,
  lat:42.3554, lng:-71.0530, url:"https://pharmstars.com",
  desc:"Digital health accelerator creating direct pathways between AI/health startups and pharmaceutical companies.",
  why:"Unique value prop: accelerates startups by providing warm intros to pharma buyers, not just mentorship. Critical for AI-health founders in the Boston biotech ecosystem.",
  tags:["digital health","pharma","healthtech"], stages:[3,4], lastVerified:"2026-06"},

{id:"ai-biohub", name:"AI BioHub (C10 Labs)", cat:"accel", loc:"Kendall Square, Cambridge",
  lat:42.3629, lng:-71.0843, url:"https://c10labs.com",
  desc:"AI-driven TechBio accelerator in Kendall Square. Partnership between C10 Labs and the biotech industry. Spring 2026 cohort active.",
  why:"Sits at the intersection of AI and life sciences — exactly where Boston's two strongest ecosystems collide. Kendall Square location provides proximity to pharma HQs.",
  tags:["biotech","AI","life sciences"], stages:[3,4], links:["c10"], lastVerified:"2026-06"},

{id:"yc-boston", name:"Y Combinator (Boston alumni)", cat:"accel", loc:"Remote / SF (Boston-based founders)", approx:true,
  lat:42.3601, lng:-71.0589, url:"https://www.ycombinator.com/companies/industry/ai/boston",
  desc:"16+ YC-funded AI startups are headquartered in Boston. While YC runs from SF, it's a critical pipeline — many founders return post-batch to build in the Boston ecosystem.",
  why:"YC's Boston alumni network is an invisible but powerful layer of the ecosystem. YC alumni dinners and founder groups are active in Cambridge.",
  tags:["top-tier","remote","alumni network"], stages:[2,3,4], lastVerified:"2026-06"},

// ---------- SPACES & HUBS ----------
{id:"cic", name:"CIC Cambridge", cat:"space", loc:"1 Broadway, Kendall Sq",
 lat:42.3629, lng:-71.0838, url:"https://cic.com",
 desc:"The original innovation campus — flexible offices and labs that have housed thousands of startups since 1999.",
 why:"The default first office for a funded Boston startup; the building itself is a networking event.",
 tags:["coworking","Kendall"], stages:[3], links:["vcafe","c10"], lastVerified:"2026-06"},
{id:"vcafe", name:"Venture Café Cambridge", cat:"space", loc:"1 Broadway, Kendall Sq",
 lat:42.3632, lng:-71.0841, url:"https://venturecafecambridge.org",
 desc:"Free Thursday-night gatherings at CIC — programming, office hours and the most reliable serendipity engine in Boston.",
 why:"Every founder's week-one move: just show up on a Thursday.",
 tags:["free","weekly"], stages:[1,2], links:["cic"], lastVerified:"2026-06"},
{id:"venturelane", name:"The Venture Lane", cat:"space", loc:"Downtown Boston", approx:true,
 lat:42.3585, lng:-71.0590, url:"https://www.theventurelane.com",
 desc:"Curated startup hub & community downtown for early-stage B2B tech.",
 why:"Smaller and more curated than big coworking — neighbors become advisors.",
 tags:["coworking","community"], stages:[3], lastVerified:"2026-06"},
{id:"foundry", name:"The Foundry (Cambridge)", cat:"space", loc:"101 Rogers St, Cambridge",
 lat:42.3690, lng:-71.0790, url:"https://thefoundrycambridge.org",
 desc:"City-backed community space for art, tech and education events in East Cambridge.",
 why:"Affordable event space for community-building workshops and demos.",
 tags:["events","community"], stages:[1], lastVerified:"2026-06"},
{id:"labcentral", name:"LabCentral", cat:"space", loc:"700 Main St North, Cambridge",
 lat:42.3626, lng:-71.0951, url:"https://www.labcentral.org",
 desc:"Shared wet-lab and office facility for early-stage life-science startups in Kendall Square, and the physical home of the AI BioHub accelerator run with C10 Labs.",
 why:"If you're building AI-for-bio, this is where the bench work happens — subsidized lab space in the densest biotech neighborhood on earth.",
 tags:["lab space","biotech","AI bio"], stages:[3], links:["c10","ai-biohub"], lastVerified:"2026-08"},

// ---------- COMMUNITIES & MEETUPS ----------
{id:"tinkerers", name:"AI Tinkerers Boston", cat:"community", loc:"Venues vary (often Kendall Sq)", approx:true,
 lat:42.3625, lng:-71.0862, url:"https://boston.aitinkerers.org",
 desc:"Hands-on meetup for people building with LLMs and agents — live demos, technical Q&A, zero fluff. Part of the global AI Tinkerers network.",
 why:"The room where Boston's AI builders actually show their work. Demo here before you launch.",
 tags:["builders","demos"], stages:[1,2,3], lastVerified:"2026-06"},
{id:"genai-meetup", name:"Boston Generative AI Meetup", cat:"community", loc:"Microsoft NERD, 1 Memorial Dr",
 lat:42.3616, lng:-71.0816, url:"https://www.meetup.com/boston-generative-ai-meetup/",
 desc:"One of the largest GenAI gatherings in New England, hosted regularly at Microsoft NERD.",
 why:"Big-tent crowd: founders, executives, researchers and artists — great for first hires and first customers.",
 tags:["genAI","networking"], stages:[1,3], links:["nerd"], lastVerified:"2026-06"},
{id:"genai-collective", name:"GenAI Collective (Boston)", cat:"community", loc:"Venues vary", approx:true,
 lat:42.3600, lng:-71.0620, url:"https://www.genaicollective.ai",
 desc:"Boston chapter of the national founder/investor GenAI community.",
 why:"Curated rooms with a high founder-to-tourist ratio.",
 tags:["founders","genAI"], stages:[1,2], lastVerified:"2026-06"},
{id:"furnace", name:"The AI Furnace (Boston)", cat:"community", loc:"Venues vary", approx:true,
 lat:42.3550, lng:-71.0600, url:"https://lu.ma/aifurnace",
 desc:"High-energy AI founder community known for demo nights and investor mixers.",
 why:"Where early AI startups get discovered by scouts and angels.",
 tags:["demos","founders"], stages:[2,4], lastVerified:"2026-06"},
{id:"pydata", name:"PyData Boston", cat:"community", loc:"Venues vary (often Cambridge)", approx:true,
 lat:42.3620, lng:-71.0855, url:"https://www.meetup.com/pydata-boston-cambridge/",
 desc:"Long-running technical meetup for the Python data/ML stack.",
 why:"Recruit senior ML engineers by giving a good talk.",
 tags:["technical","Python"], stages:[1,3], lastVerified:"2026-06"},
{id:"sundai", name:"Sundai Club", cat:"community", loc:"MIT, Cambridge", approx:true,
 lat:42.3601, lng:-71.0870, url:"https://www.sundai.club",
 desc:"MIT-born club that ships a new AI project every Sunday — students and professionals hacking side by side.",
 why:"The fastest way to find a technical cofounder may be to build with one on a Sunday.",
 tags:["hacking","weekly"], stages:[1,3], lastVerified:"2026-06"},
{id:"startupboston", name:"Startup Boston", cat:"community", loc:"Citywide", approx:true,
 lat:42.3554, lng:-71.0560, url:"https://www.startupbos.org",
 desc:"Community organization running Startup Boston Week (September) and year-round founder programming.",
 why:"The broadest on-ramp into Boston startup life beyond AI.",
 tags:["community","free"], stages:[1,2], lastVerified:"2026-06"},

// ---------- STUDENT GROUPS ----------
{id:"aimit", name:"AI@MIT", cat:"student", loc:"MIT, Cambridge", approx:true,
 lat:42.3592, lng:-71.0935, url:"https://www.aimit.club",
 desc:"MIT's undergraduate AI club — reading groups, hackathons and industry collaboration.",
 why:"Sponsor a workshop and meet your future founding engineer.",
 tags:["MIT","undergrad"], stages:[1], lastVerified:"2026-06"},
{id:"sloanai", name:"MIT Sloan AI & ML Club", cat:"student", loc:"MIT Sloan, Cambridge", approx:true,
 lat:42.3610, lng:-71.0830, url:"https://www.mitsloanaiclub.com",
 desc:"Sloan's AI club, organizer of the annual MIT Sloan AI & ML Conference.",
 why:"MBA talent that speaks both model and market.",
 tags:["MIT","MBA"], stages:[1], links:["sloan-conf"], lastVerified:"2026-06"},
{id:"maia", name:"MIT AI Alignment", cat:"student", loc:"MIT, Cambridge", approx:true,
 lat:42.3598, lng:-71.0902, url:"https://www.mitalignment.org",
 desc:"Student group focused on AI safety research and field-building.",
 why:"Boston's hub for safety-minded AI talent.",
 tags:["safety","research"], stages:[1], lastVerified:"2026-06"},
{id:"hcsai", name:"Harvard AI Safety Team", cat:"student", loc:"Harvard, Cambridge", approx:true,
 lat:42.3770, lng:-71.1167, url:"https://haist.ai",
 desc:"Harvard's AI safety student research community.",
 why:"Rigorous student researchers thinking about AI's hardest problems.",
 tags:["safety","Harvard"], stages:[1], lastVerified:"2026-06"},
{id:"neuai", name:"Northeastern AI Club", cat:"student", loc:"Northeastern, Boston", approx:true,
 lat:42.3395, lng:-71.0890, url:"https://www.neuai.club",
 desc:"Northeastern's student AI community, tied into the co-op pipeline.",
 why:"Co-op students = full-time-caliber interns for your startup.",
 tags:["co-op","students"], stages:[1], lastVerified:"2026-06"},
{id:"bumic", name:"BU Machine Intelligence Community", cat:"student", loc:"BU, Boston", approx:true,
 lat:42.3508, lng:-71.1050, url:"https://www.bumic.org",
 desc:"Boston University's ML student community.",
 why:"Eager project-hungry ML students in the middle of the city.",
 tags:["BU","students"], stages:[1], lastVerified:"2026-06"},

// ---------- MAJOR EVENTS ----------
{id:"aiweek", name:"Boston AI Week", cat:"event", loc:"Citywide · Sept 24–Oct 2, 2026",
 lat:42.3554, lng:-71.0603, url:"https://aiweek.boston", badge:"300+ events", approx:true,
 desc:"Massachusetts' flagship AI festival: 300+ events and 30,000+ participants across the state.",
 why:"The week the entire ecosystem is in one place. Plan launches, fundraising sprints and hiring pushes around it.",
 tags:["festival","September"], stages:[1,4,5], lastVerified:"2026-06"},
{id:"odsc", name:"ODSC East / AiX Summit", cat:"event", loc:"Hynes Convention Center, Boston",
 lat:42.3477, lng:-71.0858, url:"https://odsc.ai/east/",
 desc:"One of the world's largest applied data science & AI conferences, held in Boston every spring.",
 why:"Thousands of practitioners in town — recruiting and learning in one badge.",
 tags:["conference","May"], stages:[1,5], lastVerified:"2026-06"},
{id:"hackmit", name:"HackMIT", cat:"event", loc:"MIT, Cambridge",
 lat:42.3590, lng:-71.0938, url:"https://hackmit.org",
 desc:"MIT's flagship student hackathon, every fall.",
 why:"1,000+ of the best student builders in the world, in one gym, for one weekend.",
 tags:["hackathon","students"], stages:[3], lastVerified:"2026-06"},
{id:"hackharvard", name:"HackHarvard", cat:"event", loc:"Harvard, Cambridge",
 lat:42.3772, lng:-71.1170, url:"https://hackharvard.io",
 desc:"Harvard's international collegiate hackathon each October.",
 why:"Cofounder and first-hire hunting ground.",
 tags:["hackathon","students"], stages:[3], lastVerified:"2026-06"},
{id:"sloan-conf", name:"MIT Sloan AI & ML Conference", cat:"event", loc:"MIT Sloan, Cambridge", approx:true,
 lat:42.3612, lng:-71.0833, url:"https://www.aimlconference.com",
 desc:"Student-run conference connecting AI research, business and policy each spring.",
 why:"Dense one-day download of where AI-meets-business is heading.",
 tags:["conference","Sloan"], stages:[1,5], links:["sloanai"], lastVerified:"2026-06"},
{id:"imagination", name:"Imagination in Action", cat:"event", loc:"MIT Media Lab, Cambridge",
 lat:42.3608, lng:-71.0875, url:"https://www.imaginationinaction.co",
 desc:"High-wattage AI summit at the MIT Media Lab drawing global AI leaders to Cambridge.",
 why:"Davos-grade AI speakers, a T-ride away.",
 tags:["summit","AI leaders"], stages:[1,5], links:["medialab"], lastVerified:"2026-06"},
{id:"deltav-demo", name:"delta v Demo Day", cat:"event", loc:"Kresge Auditorium, MIT",
 lat:42.3583, lng:-71.0946, url:"https://entrepreneurship.mit.edu/accelerator/",
 desc:"The September showcase where MIT's delta v cohort launches to a packed house of investors.",
 why:"See what's next a year early — and meet the cohort before everyone else does.",
 tags:["demo day","September"], stages:[4], links:["deltav"], lastVerified:"2026-06"},
{id:"techweek", name:"Boston Tech Week (a16z)", cat:"event", loc:"Citywide · May", approx:true,
 lat:42.3540, lng:-71.0550, url:"https://www.tech-week.com",
 desc:"The a16z-organized decentralized tech week hit Boston in 2026 — hundreds of community-hosted events.",
 why:"A second 'whole ecosystem in one week' moment each spring.",
 tags:["festival","May"], stages:[1,4], lastVerified:"2026-06"},

// ---------- GOVERNMENT & POLICY ----------
{id:"mass-ai-coalition", name:"Massachusetts AI Coalition", cat:"gov", loc:"Boston", approx:true,
  lat:42.3554, lng:-71.0620, url:"https://massaicoalition.com",
  desc:"Industry coalition of companies advocating for responsible AI policy in Massachusetts. Hosts events, produces policy recommendations, and connects AI companies with state government.",
  why:"The bridge between Boston's AI builders and the policymakers shaping the regulatory environment. Member companies host events year-round. Essential for founders navigating AI compliance.",
  tags:["policy","advocacy","regulation"], links:["aihub"], lastVerified:"2026-06"},
{id:"masstech", name:"MassTech Collaborative", cat:"gov", loc:"75 North Drive, Westborough, MA",
  lat:42.2695, lng:-71.6162, url:"https://masstech.org",
  desc:"Quasi-public state agency driving technology innovation across Massachusetts. Manages the MA AI Hub, broadband programs, MGHPCC, and innovation economy initiatives.",
  why:"The parent organization of the MA AI Hub. Controls state-level tech funding, manages the Google AI training partnership, and runs programs that directly benefit early-stage AI founders.",
  tags:["state agency","funding","infrastructure"], links:["aihub","mghpcc"], lastVerified:"2026-06"},
{id:"aihub", name:"Massachusetts AI Hub", cat:"gov", loc:"MassTech, Boston", approx:true,
 lat:42.3604, lng:-71.0610, url:"https://aihub.masstech.org", badge:"$100M initiative",
 desc:"The state's $100M AI initiative (Mass Leads Act, launched Dec 2024): compute access, the AI Models Innovation Challenge ($3M+), and The Open Accelerator — its startup residency with Red Hat & IBM.",
 why:"Massachusetts is putting public money behind AI founders — grants, compute and programs designed for you.",
 tags:["state","$100M"], stages:[3,4], links:["mghpcc","toa","massventures"], lastVerified:"2026-06"},
{id:"mghpcc", name:"MGHPCC / AICR Compute", cat:"gov", loc:"Holyoke, MA",
 lat:42.2043, lng:-72.6162, url:"https://www.mghpcc.org", badge:"$31M compute",
 desc:"The Massachusetts Green High Performance Computing Center, now home to the state's $31M AI Compute Resources (AICR) environment for startups, universities and researchers.",
 why:"Subsidized green GPU compute. Apply for access before burning seed money on cloud bills.",
 tags:["GPUs","green compute"], stages:[3], links:["aihub"], lastVerified:"2026-06"}
];
