blank_issues_enabled: true
contact_links:
  - name: 💬 The Open Accelerator community
    url: https://the-open-accelerator.com/community/
    about: General questions about TOA programs and membership
